# Generated by Django 4.2.1 on 2023-12-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='signature',
            field=models.TextField(blank=True, default='Happy Christmas,', max_length=100),
        ),
    ]
