# Generated by Django 4.2.1 on 2023-12-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_wish_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='receiver',
            field=models.CharField(default='To *Your Receiver*', max_length=100),
        ),
        migrations.AddField(
            model_name='wish',
            name='title',
            field=models.CharField(default='*Title Of Your Wish*', max_length=100),
        ),
        migrations.AlterField(
            model_name='wish',
            name='signature',
            field=models.CharField(blank=True, default='Happy Christmas,', max_length=100),
        ),
    ]
