# Generated by Django 4.2.1 on 2023-12-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_wish_receiver_wish_title_alter_wish_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='receiver',
            field=models.CharField(default='*Your Receiver*', max_length=100),
        ),
    ]
